In [2]:
import cv2
import numpy as np

image = cv2.imread('img.jpg')

In [2]:
B, G, R = image[200,5]

print(B,G,R)

219 180 125


In [3]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [4]:
print(gray.shape)

(614, 1200)


In [5]:
V = gray[200,5]
print(V)

168


In [6]:
imgA = np.array(image,np.uint8)

In [7]:
imgG = np.sum(imgA, axis = 2)/3.2
imgG = imgG.astype(np.uint8)

In [8]:
print(imgG)

[[140 140 140 ... 127 128 128]
 [140 140 140 ... 127 128 128]
 [140 140 140 ... 127 127 127]
 ...
 [ 48  46  45 ...  50  50  78]
 [ 35  70  57 ...  75  24  70]
 [ 37  90  76 ...  53  43  78]]


## Kolory w HSV

In [9]:
image - cv2.imread('img.jpg')

hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

cv2.imshow('HSV', hsv_image)
cv2.imshow('kanal hue', hsv_image[:,:,0])
cv2.imshow('kanal saturation',hsv_image[:,:,1])
cv2.imshow('kanal value', hsv_image[:,:,2])

cv2.waitKey()
cv2.destroyAllWindows()

## Kanały RGB

In [4]:
image = cv2.imread('img.jpg')

B, G, R = cv2.split(image)

print(B.shape)

cv2.imshow('Red',R)
cv2.imshow('Green',G)
cv2.imshow('Blue',B)


merged = cv2.merge([B,G,R])
cv2.imshow('Merged', merged)

merged = cv2.merge([B+100,G,R])
cv2.imshow('wzmocniony blue', merged)

cv2.waitKey(0)
cv2.destroyAllWindows()


(614, 1200)


In [5]:
image.shape[:2]

(614, 1200)