In [2]:
import cv2
import numpy as np

In [6]:
image = cv2.imread('kontury.jpg')
cv2.imshow('obraz wejsciowy', image)
cv2.waitKey(0)

gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray,30,200)
cv2.imshow('Canny edges', edges)
cv2.waitKey(0)

contours, hierarchy = cv2.findContours(edges, cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cv2.imshow('canny edges after countouring', edges)
cv2.waitKey(0)

print(f'liczba kontorow: {len(contours)}')

cv2.drawContours(image, contours,-1,(0,255,0),3)

cv2.imshow('contours',image)
cv2.waitKey(0)

cv2.destroyAllWindows()

liczba kontorow: 11


In [7]:
print(hierarchy)

[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [ 3  1 -1 -1]
  [ 4  2 -1 -1]
  [ 5  3 -1 -1]
  [ 6  4 -1 -1]
  [ 7  5 -1 -1]
  [ 8  6 -1 -1]
  [ 9  7 -1 -1]
  [10  8 -1 -1]
  [-1  9 -1 -1]]]
